[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/in-toto/in-toto-golang"
   source = "github.com/radu-matei/in-toto-golang"
   branch = "inspections-dir"

[[constraint]]
  name = "github.com/docker/distribution"
  #version = "v2.7.1"
  revision = "0d3efadf0154c2b8a4e7b6621fff9809655cc580"

[[override]]
  name = "github.com/docker/docker-credential-helpers"
  version = "v0.6.3"

[prune]
  go-tests = true
  unused-packages = true
